export const NODE_STYLES = {
  start: {
    label: "Start",
    chip: "bg-emerald-50 text-emerald-700 border-emerald-200 hover:bg-emerald-100",
    card: "bg-emerald-50/70 border-emerald-300",
    title: "text-emerald-700",
    subtitle: "text-emerald-700/70",
    ring: "ring-emerald-400/60",
  },
  approval: {
    label: "Approval",
    chip: "bg-blue-50 text-blue-700 border-blue-200 hover:bg-blue-100",
    card: "bg-blue-50/70 border-blue-300",
    title: "text-blue-700",
    subtitle: "text-blue-700/70",
    ring: "ring-blue-500/60",
  },
  multiApproval: {
    label: "Multi-Approval",
    chip: "bg-indigo-50 text-indigo-700 border-indigo-200 hover:bg-indigo-100",
    card: "bg-indigo-50/70 border-indigo-300",
    title: "text-indigo-700",
    subtitle: "text-indigo-700/70",
    ring: "ring-indigo-500/60",
  },
  submit: {
    label: "Submit",
    chip: "bg-teal-50 text-teal-700 border-teal-200 hover:bg-teal-100",
    card: "bg-teal-50/70 border-teal-300",
    title: "text-teal-700",
    subtitle: "text-teal-700/70",
    ring: "ring-teal-500/60",
  },
  review: {
    label: "Review",
    chip: "bg-sky-50 text-sky-700 border-sky-200 hover:bg-sky-100",
    card: "bg-sky-50/70 border-sky-300",
    title: "text-sky-700",
    subtitle: "text-sky-700/70",
    ring: "ring-sky-500/60",
  },
  condition: {
    label: "Condition",
    chip: "bg-amber-50 text-amber-700 border-amber-200 hover:bg-amber-100",
    card: "bg-amber-50/70 border-amber-300",
    title: "text-amber-700",
    subtitle: "text-amber-700/70",
    ring: "ring-amber-500/60",
  },
  notify: {
    label: "Notify",
    chip: "bg-purple-50 text-purple-700 border-purple-200 hover:bg-purple-100",
    card: "bg-purple-50/70 border-purple-300",
    title: "text-purple-700",
    subtitle: "text-purple-700/70",
    ring: "ring-purple-500/60",
  },
  api: {
    label: "Integration",
    chip: "bg-orange-50 text-orange-700 border-orange-200 hover:bg-orange-100",
    card: "bg-orange-50/70 border-orange-300",
    title: "text-orange-700",
    subtitle: "text-orange-700/70",
    ring: "ring-orange-500/60",
  },
  timer: {
    label: "Timer",
    chip: "bg-surface-3 text-fg border-line hover:bg-line",
    card: "bg-surface-2 border-line",
    title: "text-fg",
    subtitle: "text-fg-muted",
    ring: "ring-gray-400/60",
  },
  end: {
    label: "End",
    chip: "bg-rose-50 text-rose-700 border-rose-200 hover:bg-rose-100",
    card: "bg-rose-50/70 border-rose-300",
    title: "text-rose-700",
    subtitle: "text-rose-700/70",
    ring: "ring-rose-500/60",
  },
};

export const NODE_TYPE_ORDER = [
  "start",
  "approval",
  "multiApproval",
  "submit",
  "review",
  "condition",
  "notify",
  "api",
  "timer",
  "end",
];

export const NODE_DEFAULTS = {
  start: { title: "Start", subtitle: "Trigger" },
  approval: {
    title: "Approval",
    subtitle: "Approval node",
    approverRole: "direct_manager",
    approverId: null,
    slaValue: 24,
    slaUnit: "Hours",
    onBreach: "Escalate to admin",
    sequential: false,
    requireSignature: false,
  },
  multiApproval: {
    title: "Committee Approval",
    subtitle: "N of M approvers",
    approverIds: [],
    requiredApprovals: 1,
    slaValue: 24,
    slaUnit: "Hours",
    requireSignature: false,
  },
  submit: {
    title: "Submit",
    subtitle: "Fill & submit",
    approverRole: "direct_manager",
    approverId: null,
    instructions: "",
    formFields: [],
    slaValue: 24,
    slaUnit: "Hours",
  },
  review: {
    title: "Review",
    subtitle: "Review & forward",
    approverRole: "direct_manager",
    approverId: null,
    instructions: "",
    slaValue: 24,
    slaUnit: "Hours",
  },
  condition: {
    title: "Decision",
    subtitle: "Branch logic",
    branches: ["Yes", "No"],
  },
  notify: {
    title: "Notify",
    subtitle: "Send notification",
    channels: ["Email"],
  },
  api: {
    title: "Integration",
    subtitle: "Call external system",
    apiUrl: "",
    apiMethod: "POST",
    apiHeaders: [],
    apiBody: "",
    apiAuth: { mode: "none" },
    saveResponseAs: "",
    continueOnError: true,
  },
  timer: {
    title: "Wait",
    subtitle: "Delay",
    waitValue: 1,
    waitUnit: "Hours",
  },
  end: { title: "End", subtitle: "Finish", generatePdf: false },
};

let _nextId = 1;
export const createNodeId = () =>
  `n${Date.now().toString(36)}${(_nextId++).toString(36)}`;
